system ('VBoxManage setproperty machinefolder /media/juan/xvms/VirtualMachines/VirtualBox/')

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.synced_folder_opts = {
      type: :nfs,
      mount_options: ['rw', 'vers=4', 'tcp', 'nolock']
    }
    # For more information please check http://docs.vagrantup.com/v2/synced-folders/basic_usage.html
  end

  # # DNS for boxes
  # if Vagrant.has_plugin?("vagrant-dns")
  #   config.dns.tld = "#{_opts["domain"]}.#{_opts["tld"]}"
  # end

  config.vm.box = "kubuntu1704"
  # config.vm.box = "ubuntu/xenial64"
  # config.vm.box = "wholebits/ubuntu17.04-64"

  # config.vm.network "private_network", ip: "172.28.128.201", virtualbox__intnet: true
  # config.vm.network "private_network", type: "dhcp", auto_config: false
  config.vm.provider :virtualbox do |vb|
    vb.gui = true
#    vb.customize ["modifyvm", :id, "--groups", "vagrant"]
  end
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.synced_folder "../../", "/srv/share", disabled: false, type: "nfs"

  #config.vm.provision "ansible" do |ansible|
  #  ansible.verbose = "v"
  #  ansible.playbook = "build.yml"
  #end

end
