# -*- mode: ruby -*-
# vi: set ft=ruby :

system ('VBoxManage setproperty machinefolder /home/juan/VirtualMachines/VirtualBox/vagrant/kfocal/')



# Load our custom configuration and prepare some global variables
# require 'yaml'
# cwd       = File.dirname(File.expand_path(__FILE__))
# ext_conf  = YAML.load_file("#{cwd}/build.yaml")
#_opts     = Hash[ext_conf.select {|hash| hash["option"] == "general"}[0]]
# machines  = ext_conf.select {|hash| hash["option"] == "machine"}
#

Vagrant.configure("2") do |config|

  # if Vagrant.has_plugin?("vagrant-cachier")
    # config.cache.scope = :box
    # config.cache.synced_folder_opts = {
      # type: :nfs,
      # owner: "_apt",
      # group: "_apt",
      # mount_options: ['rw', 'vers=4', 'tcp', 'nolock'],
      # mount_options: ["dmode=777", "fmode=666", 'rw', 'vers=4', 'tcp', 'nolock'],
    # }
    # For more information please check http://docs.vagrantup.com/v2/synced-folders/basic_usage.html
  # end

  # DNS for boxes
  #if Vagrant.has_plugin?("vagrant-dns")
  #  config.dns.tld = "#{_opts["domain"]}.#{_opts["tld"]}"
  #end

  # For Error: The following SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed!  setup
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.box = "kfocal"
  config.vm.boot_timeout = 1000

  # config.vm.network "private_network", ip: "172.28.128.201", virtualbox__intnet: true
  config.vm.network "private_network", ip: "172.28.128.111", auto_config: false
  # config.vm.network "private_network", type: "dhcp", auto_config: false
  config.vm.provider :virtualbox do |vb|
    vb.gui = true
#    vb.customize ["modifyvm", :id, "--groups", "vagrant"]
    vb.memory = "2048"
  end

  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.synced_folder "../../../", "/srv/share/build", disabled: false, type: "nfs"
  config.vm.synced_folder "/home/juan/Downloads/", "/srv/share/downloads", disabled: false, type: "nfs"
  config.vm.synced_folder "/media/juan/xvms/Movies/", "/srv/share/movies", disabled: false, type: "nfs"
  #config.vm.synced_folder "/media/juan/xvms/cache/focal/apt/archives/", "/var/cache/apt/archives/", type: "rsync",
  #  rsync__exclude: ["partial/", "lock"],
  #  rsync__args: ["--verbose", "--rsync-path='sudo rsync'", "--archive", "-z", "-P"]
  config.vm.provision "shell", inline: <<-SHELL
     sed -i 's/allowed_users=.*$/allowed_users=anybody/' /etc/X11/Xwrapper.config
     apt-get update
     apt-get -y upgrade
     apt-get -y dist-upgrade
     apt-get -y full-upgrade
     apt-get -yf install
   SHELL


  #config.vm.provision "ansible" do |ansible|
  #  ansible.verbose = "v"
  #  ansible.playbook = "build.yml"
  #end

end
